config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :registrations => "user/registrations"}
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "pages#home"
  get "my_portfolio", to: "users#my_portfolio"

  get "search_stocks", to: "stocks#search"

  resources :user_stocks, only: [:create, :destroy]
  resources :users, only:[:show]
  resources :friendships
  get "search_friends", to: "users#search"

  get "my_friends", to: "users#my_friends"

  # a route to add_my_friend to users controller action add_friend
  post "add_friend", to: "users#add_friend"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, :class_name => 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord

  def self.new_from_lookup(ticker_symbol)
    begin
      looked_up_stock = StockQuote::Stock.quote(ticker_symbol)
      new(name: looked_up_stock.company_name, ticker: looked_up_stock.symbol, last_price: looked_up_stock.latest_price)
    rescue Exception => e
      return nil
    end
  end

  has_many :user_stocks
  has_many :users, through: :user_stocks

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    return "#{first_name} #{last_name}".strip if (first_name || last_name)
    "Anonymous"
  end

  def stock_already_added?(ticker_symbol)
    stock = Stock.find_by_ticker(ticker_symbol)
    return false unless stock
    user_stocks.where(stock_id: stock.id).exists?
  end

  def under_stock_limit?
    (user_stocks.count < 10)
  end

  def can_add_stock?(ticker_symbol)
    under_stock_limit? && !stock_already_added?(ticker_symbol)
  end

  # Define a function named search that can strip whitespaces and downcase the params[:search_param]
  # return a nil if id doesnt exist or return a variable
  def self.search(param)
    param.strip!
    param.downcase!
    User.where('first_name LIKE ?', "%#{param}%")
        .or(User.where('last_name LIKE ?', "%#{param}%"))
        .or(User.where('email LIKE ?', "%#{param}%"))
  end

  #a function that matches field name and param
  def self.matches(field_name, param)
    User.where("#{field_name} LIKE ?", "#{param}")
  end

  def except_current_user(users)
    users.reject {|user| user.id == self.id}
  end

  def not_my_friends_with?(friend_id)
    friendships.where(friend_id: friend_id).count < 1

  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception
  # For APIs, you may want to use :null_session instead
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

  def destroy
    #grab the realtionship in an instance from the friendships table
    @friendship = current_user.friendships.where(friend_id: params[:id]).first
    @friendship.destroy
    redirect_to my_friends_path
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home

  end

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock].blank?
        flash.now[:danger]= "You have entered an empty search string "
    else
      @stock = Stock.new_from_lookup(params[:stock])
      flash.now[:danger]= "You have entered an incorrect symbol" unless @stock
    end
    respond_to do |format|
      format.js {render partial: 'users/result'}
    end
  end


end

app/controllers/user/registrations_controller.rb
class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys:[:first_name, :last_name])
  end
end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.find_by_ticker(params[:stock_ticker])
    if stock.blank?
      stock = Stock.new_from_lookup(params[:stock_ticker])
      stock.save
    end
    @user_stocks = UserStock.create(user: current_user, stock: stock)
    flash[:success]="#{@user_stocks.stock.name} was successfully add to your portfolio"
    redirect_to my_portfolio_path
  end

  def destroy
    stock = Stock.find(params[:id])
    @user_stock = UserStock.where(user_id: current_user.id, stock_id: stock.id).first
    @user_stock.destroy
    flash[:notice] = "Stock was succesfully removed from the portfolio"
    redirect_to my_portfolio_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_portfolio
    @user = current_user
    @user_stocks = current_user.stocks
  end

  def my_friends
    @friendships = current_user.friends
  end

  def search
    # grab the parameter of the search, find the user and store it in a
    # instance variable --> go to user model to define search()
    # @users = User.search(params[:search_param])
    # render a json at user
    # render json: @users
    # grab the search code from search stock and make it useable for friends
    if params[:search_param].blank?
      flash.now[:danger] = "You entered a blank statement "
    else
      @users = User.search(params[:search_param])
      @users = current_user.except_current_user(@users)
      flash.now[:danger] = "The user you are looking for does not exist" if @users.blank?
    end
    respond_to do |format|
      format.js {render partial: 'friends/result'}
    end
  end

  def add_friend
    # grab a instance variable friend
    @friend = current_user.friendships.where(friend_id: params[:friend])
    # build the friendship association
    current_user.friendships.build(friend_id: params[:friend])
    # if you are able to sabe the friendship association
    if current_user.save

      # friend was succesfully added
      flash[:success]= "Succesfully added as friend"
      redirect_to my_friends_path

    else
      # there was something wrong with the friend request
      flash[:notice] = "Something went wrong"
      # redirecto to the page that show the search bar and the friends list
      redirect_to my_friends_path
    end
    #----------------------------------------------------------------------------
    # add a function that called not_my_friends_with? with a parameter (friend_id)
    # look if i am already friends with him or not

  end

  def show
    # select the use that want you wan to view ans create a new template
    @user = User.find(params[:id])
    @user_stocks = @user.stocks
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_stocks_helper.rb
module UsersStocksHelper
end

app/views/friends/_lookup.html.erb
<h1>My Friends</h1>


<h3>Search for friends</h3>


<div id= "friend-lookup">

  <%= form_tag search_friends_path, remote: true, method: :get, id: "friend-lookup-form" do %>
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-10">
        <%= text_field_tag :search_param, params[:seach_param], placeholder:
        "Enter name or email", autofocus: true, class: "form-control search-box input-lg"%>
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <span class="glyphicon glyphicon-search"></span> Search
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="results">
  <%= render 'friends/result' %>
</div>

app/views/friends/_result.html.erb
<% if params[:action] == 'search' %>
  <div class="result-block">
    <%= bootstrap_flash %>
  </div>
<% end %>
<% if !@users.blank? %>
  <div id="friend-lookup-results"class="well results-block col-md-10">
    <table class="search-results-table col md 12" width="100%">
      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><strong>Name:</strong> <%= user.full_name %> </td>
            <td><strong>Email:</strong> <%= user.email %> </td>
            <td><strong>Profile:</strong> <%= link_to "View Profile", user_path(user), class: "btn btn-xs btn-success" %>
                                          <% if current_user.not_my_friends_with?(user.id) %>
                                            <%=link_to "Add as Friend", add_friend_path(user: current_user.id, friend: user.id),
                                                                         class: "btn btn-xs btn-success",
                                                                         method: :post%></td>

                                            <% else %>
                                            <span class="label label-primary">
                                              You are already friends
                                            </span>
                                            <% end %>

          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
<% end %>

app/views/friends/_result.js.erb
$('#results').html("<%= j (render 'friends/result.html')%>")

app/views/layouts/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <%= link_to 'Finance Tracker', root_path, class: "navbar-brand" %>
    <% if current_user %>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-collapse collapse navbar-responsive-collapse">
        <ul class="nav navbar-nav">
          <li><%= link_to "My Portfolio", my_portfolio_path  %></li>
          <li><%= link_to "Edit profile", edit_registration_path(current_user)  %></li>
          <li><%= link_to "My friends", my_friends_path  %></li>
        </ul>
        <ul class="nav navbar-right col-md-4">
          <li class="col-md-8 user-name text-right">
            <i class="fa fa-user"></i>
            <%= current_user.full_name.present? ? current_user.full_name : current_user.email %>
          </li>
          <li class = "col-md-4 logout">
            <%= link_to("Log out", destroy_user_session_path, class: "btn btn-xs btn-danger", method: :delete) %>
          </li>
        </ul>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "FinanceTracker" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <%= render 'layouts/navigation'%>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2019</p>
      </footer>

    </div> <!-- /container -->
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to track app IMBECil </h1>

<%= link_to "logout", destroy_user_session_path, method: :delete %>

app/views/stocks/_list.html.erb
<% if !@user_stocks.blank? %>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Symbol</th>
        <th>Current Price</th>
        <% if @user.id == current_user.id %>
          <th>Actions</th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @user_stocks.each do |user_stock|%>
        <tr>
          <td><%= user_stock.name %></td>
          <td><%= user_stock.ticker %></td>
          <td><%= user_stock.last_price %></td>
          <% if @user.id == current_user.id %>
            <td><%= link_to "Delete the stock", user_stock_path(user_stock), method: :delete,
              data: {confirm:"Are you sure?"}, class:"btn btn-xs btn-danger"%></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <h2>He doesn't follow any stocks</h2>  
<% end %>

app/views/users/_result.html.erb
<% if params[:action] == 'search' %>
  <div class="result-block">
    <%= bootstrap_flash %>
  </div>
<% end %>
<% if @stock %>
  <div class="well result-block">
    <strong>Symbol: </strong><%= @stock.ticker %>
    <strong>Name: </strong><%= @stock.name %>
    <strong>Price: </strong><%= @stock.last_price %>
    <% if current_user.can_add_stock?(@stock.ticker) %>
      <%= link_to "Add to my stocks", user_stocks_path(user: current_user, stock_ticker: @stock.ticker), class: "btn btn-s btn-success", method: :post %>
    <% else %>
      <span class="label label-default">
        Stock cannot be added because you have already added
        <% if !current_user.under_stock_limit?
        debugger%>
          10 stocks

        <% end %>
        <% if current_user.stock_already_added?(@stock.ticker) %>
          this stocks
          <% end %>
      </span>
    <% end %>
  </div>
<% end %>

app/views/users/_result.js.erb
$('#results').html("<%= j (render 'users/result.html')%>")

app/views/users/my_friends.html.erb
<%=render 'friends/lookup' %>
<% if @friendships.size > 0 %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th class="page-header" colspan="3">
          <h2>My friends</h2>
        </th>
      </tr>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Actions</th>
      </tr>
    </thead>

    <tbody>
      <% @friendships.each do |friend|%>
        <tr>
          <td><%= friend.full_name %></td>
          <td><%= friend.email %></td>
          <td>
            <%= link_to "View Profile", user_path(friend), class:"btn btn-primary btn-xs" %>
            <%= link_to "Remove Friends", friendship_path(friend),
                                          method: :delete,
                                          data: {confirm:"Are you sure?"},
                                          class:"btn btn-xs btn-danger"%>
          </td>
        </tr>
      <% end %>
    </tbody>

  </table>
<% else %>
  <div class="row col-lg-12">
    <p class="lead">You dont have any friends yet. Please add some more!</p>
  </div>
<% end %>

app/views/users/my_portfolio.html.erb
<h1>My Portfolio</h1>


<h3>Search for stocks</h3>


<div id= "stock-lookup">

  <%= form_tag search_stocks_path, remote: true, method: :get, id: "stock-lookup-form" do %>
    <div class="form-group row no-padding text-center col-md-12">
      <div class="col-md-10">
        <%= text_field_tag :stock, params[:stock], placeholder:
        "Stock ticker symbol", autofocus: true, class: "form-control search-box input-lg"%>
      </div>
      <div class="col-md-2">
        <%= button_tag(type: :submit, class: "btn btn-lg btn-success") do %>
          <span class="glyphicon glyphicon-search"></span> Look up a stock
        <% end %>
      </div>
    </div>
  <% end %>
</div>

<div id="results">
  <%= render 'users/result' %>
</div>

<%= render 'stocks/list' %>

app/views/users/show.html.erb
<h1>User Details</h1>

<dl class="dl-horizontal">
  <dt><strong>Full name</strong></dt>
  <dd><%= @user.full_name %></dd>
  <dt><strong>Email</strong></dt>
  <dd><%= @user.email%></dd>
</dl>

<%= render 'stocks/list' %>